### PR TITLE
Solve the bug of dead lock when restore state 

### PR DESCRIPTION
**Pull request by CFAndy**
Fix the start iter_ for slave solver when the root solver restore state from binary file .
This will cause deadlock when using NCCL

### CODE REVIEW

**Comment by CFAndy** [comment]
After doing the testAll, the root solver will enter into barrier wait state. 
At first, I though it was a NCCL issue. But it turned out to be a bug of Caffe.

**Comment by fucevin** [comment]
I met this issue  every time. But this bug doesn't impact digits, why?

**Comment by drnikolaev** [comment]
@ChenFengAndy could you please check 0.16 branch?

**Comment by CFAndy** [comment]
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 0000:02:00.0     Off |                  N/A |
| 23%   27C    P8     9W / 250W |   7159MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 0000:03:00.0     Off |                  N/A |
| 23%   23C    P8    10W / 250W |   9723MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    Off  | 0000:82:00.0     Off |                  N/A |
| 23%   28C    P8     9W / 250W |   9723MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN X (Pascal)    Off  | 0000:83:00.0     Off |                  N/A |
| 23%   26C    P8     9W / 250W |   9723MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     11240    C   /root/caffe/build/tools/caffe                 7151MiB |
|    1     11240    C   /root/caffe/build/tools/caffe                 9715MiB |
|    2     11240    C   /root/caffe/build/tools/caffe                 9715MiB |
|    3     11240    C   /root/caffe/build/tools/caffe                 9715MiB |

I0606 14:26:59.799461 18501 sgd_solver.cpp:108] Iteration 234960, lr = 0.053008
I0606 14:27:21.995661 18501 solver.cpp:441] Iteration 235000, Testing net (#0)
I0606 14:28:05.918299 18499 data_reader.cpp:140] Restarting data pre-fetching

**Comment by CFAndy** [comment]
still there

**Comment by drnikolaev** [comment]
Thanks, reopening. Was this state file created in 0.15 release?

**Comment by ChenFengAndy** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 0000:06:00.0     Off |                  Off |
| N/A   52C    P0    49W / 300W |  14595MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  On   | 0000:07:00.0     Off |                  Off |
| N/A   45C    P0    46W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  On   | 0000:0A:00.0     Off |                  Off |
| N/A   47C    P0    45W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  On   | 0000:0B:00.0     Off |                  Off |
| N/A   42C    P0    45W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P100-SXM2...  On   | 0000:85:00.0     Off |                  Off |
| N/A   43C    P0    45W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P100-SXM2...  On   | 0000:86:00.0     Off |                  Off |
| N/A   41C    P0    45W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P100-SXM2...  On   | 0000:89:00.0     Off |                  Off |
| N/A   49C    P0    48W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P100-SXM2...  On   | 0000:8A:00.0     Off |                  Off |
| N/A   45C    P0    43W / 300W |  16253MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     46314    C   ./build/tools/caffe                          14589MiB |
|    1     46314    C   ./build/tools/caffe                          16247MiB |
|    2     46314    C   ./build/tools/caffe                          16247MiB |
|    3     46314    C   ./build/tools/caffe                          16247MiB |
|    4     46314    C   ./build/tools/caffe                          16247MiB |
|    5     46314    C   ./build/tools/caffe                          16247MiB |
|    6     46314    C   ./build/tools/caffe                          16247MiB |
|    7     46314    C   ./build/tools/caffe                          16247MiB |
+-----------------------------------------------------------------------------+

**Comment by CFAndy** [comment]
caffe-0.16+cuDNNv6

**Comment by CFAndy** [comment]
do you want me to test my fix on 0.16 or you can fix it?

**Comment by CFAndy** [comment]
create a fix for 0.16 #350.

**Comment by drnikolaev** [comment]
Fixed in v0.16.2

**Pull request closed without merging**
