### PR TITLE
Fixed build failure on power arch by replacing pause instruction with…

### PR DESCRIPTION
**Pull request by npanpaliya**
… or 27,27,27

### CODE REVIEW

**Comment by npanpaliya** [comment]
The build failure due to earlier changes has been fixed. Can anyone please let me know how can I trigger All Checks again for my pull request?

**Comment by lukeyeager** [comment]
```
git checkout inline-assembly-fix
git rebase nvidia/caffe-0.15
git push -f
```

**Comment by npanpaliya** [comment]
Thanks @lukeyeager .

**Comment by npanpaliya** [comment]
Hello,

Could anyone please review this PR?

**Comment by hit1001** [comment]
Does it goes with the same for aarch64 ? Bcz i got the similar error while compiling on aarch64 with cuDNN v5.1 and CUDA 8.0 ?

**Comment by npanpaliya** [comment]
I'm sorry, I do not have any experience with aarch64. You may try with this PR if it works for you on aarch64.

**Comment by hit1001** [comment]
@npanpaliya No it doesnt work.

**Comment by npanpaliya** [comment]
Is pause instruction or its equivalent implemented for your processor?

**Comment by drnikolaev** [comment]
Done

**Pull request closed without merging**
