### PR TITLE
Add SSD Object detection

### PR DESCRIPTION
**Pull request by mathmanu**
Single Shot Multibox detector (https://arxiv.org/abs/1512.02325, https://github.com/weiliu89/caffe/tree/ssd) is an important algorithm for machine learning and computer vision.

SSD is currently not integrated into caffe. It exists in one form of BVLC/caffe. Significant effort was needed to port it into NVIDIA/caffe (due to the changes that happened in NVIDIA/caffe recently).

This pull rquest will enable SSD object detection in NVIDIA/caffe.

### CODE REVIEW

**Comment by mathmanu** [comment]
I am not familiar with Travis CI.  Could some one please explain what is the error being reported and how to fix it? Thanks.

**Comment by ashwin** [comment]
@mathmanu Could you add support for `global_grad_scale` to the SSD loss layer?

It is quite surprising that NVIDIA talks about this in their [multi-precision training guide](http://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html) (for V100), but has not shared the loss layer code to achieve this.

@drnikolaev could you share the changes needed to make SSD detection mixed-precision training work on DGX1/V100? Setting `global_grad_scale: 256.0` as suggested in your [talk slides](http://on-demand.gputechconf.com/gtc-il/2017/presentation/sil7116-boris-ginsburg-mixed-precision-training-of-deep-nn-with-volta.pdf) or guide does not train. You must have done changes to other layers and code of SSD to get the results you present in your slides. Could you share those changes? Or at least give us information on how to make the changes?

**Comment by mathmanu** [comment]
I think having SSD object detection integrated in caffe is a big value addition and I willing to contribute wherever needed.

However, I don't have much idea about global_grad_scale. I also doesn't have a mixed precision machine - I have GTX 1080. So, can't do much here.

**Comment by ashwin** [comment]
@mathmanu Have you confirmed that a model trained with your nvcaffe port of SSD matches the mAP of a model trained with BVLC Caffe? ⚖️

**Comment by mathmanu** [comment]
Some clarifications:

1. Tried out some of my custom configurations - and it trains well and produces good results. However I have not tried to reproduce the original mAP of the VGG based SSD model published by Wei Liu. It should be possible as there are no changes in this port that alter the functionality. 

2. Have not tried with FP16 data type. I tried only with the default (float) data types.

3. NVIDIA/caffe allows forward, backward and math types to be different. However BVLC/caffe doesn't support this. This porting over may not be perfect - so, these SSD layers may not work correctly if you use different types (forward, backward, math) in these SSD layers. Fixing this need careful attention to be spend on the Backward functions of some of these SSD layers.

The time that I can spend on this is limited. I would be grateful if someone could work one these aspects and remove the limitations.

**Comment by nViso** [comment]
SSD would be a good addition to NVCaffe especially with FP16 support as object detection is so computationally heavy. There have been several papers this year extending SSD performance for object detection tasks.

**Comment by drnikolaev** [comment]
@mathmanu thank you. What was the reason to change reader and transformer? Do you have any model using SSD in order to put it to models collection?

**Comment by mathmanu** [comment]
@drnikolaev Object detection has different kind of labels/annotation compared to classification. SSD object detection uses a data type for storing the input data and the corresponding annotation - called AnnotatedDatum instead of Datum (which is used in classification). 

In order to support AnnotatedDatum, data_reader was made generic. db_leveldb.hpp and db_lmdb.hpp was also modified for this purpose.

Transformer was modified to support data augmentations on AnnotatedDatum. Some additional data augmentations used by SSD were also added.

**Comment by drnikolaev** [comment]
@mathmanu @ashwin @nViso thank you folks, I'll do my best to merge this. But I need a model and dataset for testing. Please upload at least one good set of prototxt files to start with.

**Comment by mathmanu** [comment]
@drnikolaev Kindly give me couple of days. I'll add commits to the pull request with the information that you requested.

**Comment by mathmanu** [comment]
The datasets, scripts and sample prototxts for using SSD object detection are available in:
https://github.com/weiliu89/caffe/tree/ssd

The links for models are given the "Models"section.

For example, user the "Models"section, you can find a model named 07+12 SSD500, with the following link:  https://drive.google.com/open?id=0BzKzrI_SkD1_ZDIxVHBEcUNBb2s

**Comment by mathmanu** [comment]
Let me know any help that you need. After you merge, I can run it and make sure that it works.

**Comment by drnikolaev** [comment]
@mathmanu thanks. We'll stay in touch.

**Comment by bonseyes-admin** [comment]
Hi, How are you getting on with SSD integration? It would be good to integrate MobileNet + SSD. A Caffe based example is here: https://github.com/chuanqi305/MobileNet-SSD

**Comment by drnikolaev** [comment]
@bonseyes-admin @mathmanu would you be able to have a look at pre-release?

**Comment by mathmanu** [comment]
Sure. Where is it?

**Comment by drnikolaev** [comment]
@mathmanu still composing 0.17 release, coming soon. I'd like to get rid of `RepeatedPtrField` -- why don't you use `vector` instead?

**Comment by mathmanu** [comment]
I didn't modify this part - it is as it is, in the original implementation: https://github.com/weiliu89/caffe/tree/ssd
May be @weiliu89 can answer.

**Comment by drnikolaev** [comment]
@mathmanu here: https://github.com/drnikolaev/caffe/tree/caffe-0.17
It has SSD, Deconv, RNN...
SSD is slow in TEST phase (I did some optimizations but still slow)
Please consider adding more tests (especially for those new layers)

**Comment by bonseyes-admin** [comment]
@drnikolaev - thanks we will test SSD as well.

**Comment by drnikolaev** [comment]
v0.17.0

**Pull request closed without merging**
