### PR TITLE
GPU Memory Manager refactored

### PR DESCRIPTION
**Pull request by drnikolaev**
This refactoring was made to address some concerns raised by BVLC folks.

### CODE REVIEW

**Comment by drnikolaev** [comment]
@thatguymike thanks for the review

**Comment by lukeyeager** [comment]
Why did you check in this file?
`python/caffe/imagenet/ilsvrc_2012_mean.npy`

**Comment by drnikolaev** [comment]
@lukeyeager 
$ git blame python/caffe/imagenet/ilsvrc_2012_mean.npy | head -n1
47ec9ace (Evan Shelhamer 2014-04-09 18:33:18 -0700    1) �NUMPYF{'descr': '<f8', 'fortran_order': False, 'shape': (3, 256, 256), }   

So, it's there for more than 2 years and I managed to move it. Now, the question is: should we return it back or delete it?

**Comment by lukeyeager** [comment]
I don't like the new error message when I run out of memory.
Any way we can go back to a good old "out of memory" error?

```
F0616 13:29:28.951283 12145 gpu_memory.hpp:77] Check failed: try_reserve(size)
```

detectnet-out-of-memory-bad-error

**Comment by drnikolaev** [comment]
@lukeyeager Please file me a bug for this. Would `LOG(FATAL) << "Out of memory"` look better?

**Pull request merged**
