### PR TITLE
Fix gradient accumulation for cuDNN convolution layer

### PR DESCRIPTION
**Pull request by slayton58**
Fixes the gradient accumulation issue in CuDNNConvolutionLayer reported in caffe BVLC/caffe/pull/3254

### CODE REVIEW

**Comment by lukeyeager** [comment]
Why not just cherry-pick @ronghanghu's commit? Commenting rather than deleting those lines may lead to a merge conflict down the road.

Also, why did you change the test if it wasn't needed in BVLC/caffe/pull/3254?

**Comment by slayton58** [comment]
I changed the gradient file to match what is in bvlc today, and without it the convolution tests fail

**Comment by lukeyeager** [comment]
Oh sorry, I didn't notice this was for the `master` branch. I wish @github would make that a little more obvious somehow.

So we need this fix in the `caffe-0.14` branch, too?

**Comment by lukeyeager** [comment]
Merged into `master` and `caffe-0.13`.

**Pull request merged**
