### PR TITLE
Getting changes from the latest bvlc branch for OSX

### PR DESCRIPTION
**Pull request by trivedigaurav**
Includes changes from the latest version on bvlc's caffe branch to build proper libs on Mac OS.

### CODE REVIEW

**Comment by lukeyeager** [comment]
Did you just revert all the changes in the NVIDIA fork? How does that solve your problem at https://github.com/NVIDIA/DIGITS/pull/87?

The only commits to the Makefile in BVLC/caffe `v0.11.0` was tagged are c6414ea,  797587d and caaf321. None of those are relevant. 

> Includes changes from the latest version on bvlc's caffe branch to build proper libs on Mac OS.

So, what do you mean by this?

**Comment by trivedigaurav** [comment]
Luke: Now that you pointed me to the changes that are not included in the
Nvidia branch, it doesn't make much sense but somehow Nvidia's makefile is
causing to build invalid lib files on MacOS. If I build caffe with it, I
get the following error:

```
dyld: Library not loaded: libcaffe-nv.so.0
  Referenced from:
/Users/trivedigaurav/data/Projects/caffe/.build_release/tools/caffe
  Reason: image not found
```

Maybe you can take a closer look at what's causing this... I didn't do that.

**Comment by lukeyeager** [comment]
Ah, so you're running into the same problem that these guys had:

https://groups.google.com/d/msg/caffe-users/Hi4HKumNIdM/Quts79ZmLJUJ

https://github.com/NVIDIA/DIGITS/issues/46

I'll add a new issue for getting this fixed. I'm going to close this PR as this is not the correct solution.

**Comment by trivedigaurav** [comment]
Sure. But I don't think folks managed to close the issue there. So, it may
be worth taking a look at the Makefile once again.

**Comment by lukeyeager** [comment]
You're right. I'm saying we broke the build system for Mac and didn't realize it because we haven't been testing for Mac. We'll get this fixed for the next NVIDIA/caffe release so that you can at least build and run caffe properly on OSX, but it still may not be "officially" supported for DIGITS.

**Pull request closed without merging**
